In [16]:
import numpy as np

In [17]:
arr=np.array([0,1,2,3,4,5])   #creating an array

In [18]:
arr

array([0, 1, 2, 3, 4, 5])

In [19]:
arr=np.array([10,1,2,3,4,5],np.int8) #can also add dtype to the array elements 
arr

array([10,  1,  2,  3,  4,  5], dtype=int8)

In [20]:
arr[0]

np.int8(10)

In [21]:
print(arr[0])

10


In [23]:
arr_2d=np.array([[1,2,3,4]])

In [24]:
arr_2d[0]

array([1, 2, 3, 4])

In [25]:
arr_2d[0,3]

np.int64(4)

In [26]:
arr_2d.shape

(1, 4)

In [27]:
arr_2d.dtype

dtype('int64')

<h1 style="font-size:50px;">Ways to create an array</h1>


In [28]:
obj=np.array({2,3,4,2})

**avoid object type data in data science**

In [29]:
obj

array({2, 3, 4}, dtype=object)

In [34]:
zero=np.zeros((2,5)) #matrix full of zero

In [35]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
range=np.arange(15) #gives a range

In [38]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
lspace=np.linspace(2,15,10) #same spacing between number, useful for bins??

In [45]:
lspace

array([ 2.        ,  3.44444444,  4.88888889,  6.33333333,  7.77777778,
        9.22222222, 10.66666667, 12.11111111, 13.55555556, 15.        ])

In [50]:
emp=np.empty(2)  #create an empty array
emp1=np.empty((5,6))

In [52]:
emp

array([2.00000000e+000, 6.54077441e-310])

In [53]:
emp1

array([[5.15608347e-310, 0.00000000e+000, 6.54077538e-310,
        6.54079127e-310, 6.54077538e-310, 6.54079127e-310],
       [6.54077538e-310, 6.54079127e-310, 6.54077538e-310,
        6.54079127e-310, 6.54077538e-310, 6.54079127e-310],
       [6.54077538e-310, 6.54079127e-310, 6.54077538e-310,
        6.54079127e-310, 6.54077538e-310, 6.54079127e-310],
       [6.54077538e-310, 6.54077538e-310, 6.54079128e-310,
        6.54079127e-310, 6.54079128e-310, 6.54077538e-310],
       [6.54079128e-310, 6.54079127e-310, 6.54079128e-310,
        6.54077538e-310, 6.54079128e-310, 6.54079127e-310]])

In [54]:
emp_like=np.empty_like(range)

In [56]:
emp_like

array([104360297825816,               0,               0,               0,
                     0,               0,               0,               0,
                     0,               0,               0,               0,
                     0,               0,             128])

In [57]:
ide=np.identity(20)

In [58]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [59]:
ide.shape

(20, 20)

<h1 style="font-size:30px;">Some useful functions</h1>


In [60]:
demn=np.arange(99)

In [61]:
demn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [68]:
demn=demn.reshape(3,33)

In [69]:
demn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [70]:
demn.shape

(3, 33)

In [71]:
demn=demn.ravel()

In [72]:
demn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [73]:
demn.shape

(99,)

<h1 style="font-size:30px;">About axis and some more important functions</h1>

In [74]:
p=[[1,5,8],[3,2,4],[9,0,5]]

In [75]:
ar=np.array(p)

In [76]:
ar

array([[1, 5, 8],
       [3, 2, 4],
       [9, 0, 5]])

In [77]:
ar.sum(axis=0)

array([13,  7, 17])

In [78]:
ar.sum(axis=1)

array([14,  9, 14])

In [80]:
ar.T #transpose method

array([[1, 3, 9],
       [5, 2, 0],
       [8, 4, 5]])

In [81]:
ar.flat #gives an iterator

In [83]:
for i in ar.flat:
    print(i)

1
5
8
3
2
4
9
0
5


In [84]:
ar.ndim #array dimension

2

In [85]:
ar.size

9

In [86]:
ar.nbytes  #total bytes consume

72

In [87]:
op=np.array([3,5,2,654,0])

In [91]:
op.argmax()  #gives index of max element

np.int64(3)

In [92]:
op.argmin() #gives index of min element

np.int64(4)

In [94]:
op.argsort() #gives indices on bases of how array can be sort

array([4, 2, 0, 1, 3])

In [95]:
ar

array([[1, 5, 8],
       [3, 2, 4],
       [9, 0, 5]])

In [96]:
ar.argmax()

np.int64(6)

In [97]:
ar.argmin()

np.int64(7)

In [98]:
ar.argmax(axis=0)

array([2, 0, 0])

In [99]:
ar.argmin(axis=1)

array([0, 1, 1])

In [101]:
ar.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [1, 2, 0]])

In [102]:
ar.argsort(axis=0)

array([[0, 2, 1],
       [1, 1, 2],
       [2, 0, 0]])

In [103]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [1, 0, 2],
       [1, 2, 0]])

<h1 style="font-size:30px;">Mathematical operations</h1>

In [105]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [107]:
ar

array([[1, 5, 8],
       [3, 2, 4],
       [9, 0, 5]])

In [108]:
ar+ar2 #matrix addition

array([[ 2,  7, 11],
       [ 7,  7, 10],
       [16,  8, 14]])

ar*ar2 #element wise multiplication

In [111]:
np.sqrt(ar)

array([[1.        , 2.23606798, 2.82842712],
       [1.73205081, 1.41421356, 2.        ],
       [3.        , 0.        , 2.23606798]])

In [112]:
ar.sum()

np.int64(37)

In [113]:
ar.max()

np.int64(9)

In [114]:
ar.min()

np.int64(0)

In [115]:
np.where(ar>5)

(array([0, 2]), array([2, 0]))

In [116]:
np.count_nonzero(ar)

8

In [117]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 2]))

<h1 style="font-size:30px;">These were just some basic function and kind of like a intro to numpy, to keep learning new stuff in the numpy library visit sites like w3schools or scipy docs </h1>